
export const ActionTypes = {

    /*login */
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN__FAILURE',

    /*register*/
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    USER_LOGOUT: 'USER_LOGOUT',

    /*get product category */
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',

    GET_CATEGORY_ID: 'GET_CATEGORY_ID',

    /*product list  */
    GET_PRODUCT_LIST_REQUEST: 'GET_PRODUCT_LIST_REQUEST',
    GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST_SUCCESS',
    GET_PRODUCT_LIST_FAILURE: 'GET_PRODUCT_LIST_FAILURE',

    /*product details*/
    GET_PRODUCT_DETAILS_SUCCESS:'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAILURE:'GET_PRODUCT_DETAILS_FAILURE',

    //update star rating
    UPDATE_PRODUCT_RATING_SUCCESS: 'UPDATE_STAR_PRODUCT_SUCCESS',

    /* rate to product*/
    RATE_TO_PRODUCT: 'RATE_TO_PRODUCT',


    /* Add product to cart */
    ADD_PRODUCT_TO_CART_REQUEST:'ADD_PRODUCT_TO_CART_REQUEST',
    ADD_PRODUCT_TO_CART_SUCCESS:'ADD_PRODUCT_TO_CART_SUCCESS',
    ADD_PRODUCT_TO_CART_FAILURE:'ADD_PRODUCT_TO_CART_FAILURE',

    /*get cart data*/
    GET_CART_DATA_SUCCESS: 'GET_CART_DATA_SUCCESS',

    /*place order */
    PLACE_ORDER_SECCESS: 'PLACE_ORDER_SECCESS',
    PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',


    /*user Profile */
    GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
    GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

    /*Edit profile*/
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    /*Edit profile*/

    /*address*/
    ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',

    GET_CUST_ADDRESS_REQUEST: 'GET_CUST_ADDRESS_REQUEST',
    GET_CUST_ADDRESS_SUCCESS: 'GET_CUST_ADDRESS_SUCCESS',
    GET_CUST_ADDRESS_FAILURE: 'GET_CUST_ADDRESS_FAILURE',

    SAVE_ADDRESS_SUCCESS: 'SAVE_ADDRESS_SUCCESS',
    SAVE_ADDRESS_FAILURE: 'SAVE_ADDRESS_FAILURE',
    /*address*/

    /*forgot pwd and set pwd */
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
    RECOVER_PASSWORD_FAILURE: 'RECOVER_PASSWORD_FAILURE',
    /*forgot pwd and set pwd */

    /*change password*/
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    /*change password*/

    /*get all products */
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    /*get all products */

    /*get Order Details*/
    GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS',
    /*getOrderDetails*/

    
}